---
- name: Exécuter la commande "composer-cli compose start-ostree --ref rhel/8/x86_64/edge kiosk edge-commit"
  hosts: all
  become: true  # Utilisez "become: true" si une élévation des privilèges est nécessaire

  tasks:
    - name: Exécuter la commande "composer-cli compose start-ostree --ref rhel/8/x86_64/edge kiosk edge-commit"
      command: "composer-cli compose start-ostree --ref rhel/8/x86_64/edge kiosk edge-commit"
      register: output  # Enregistrez la sortie de la commande dans une variable

    - name: Afficher la sortie de la commande
      debug:
        var: output.stdout_lines
        register: output

    - name: Extraire l'ID du compose
      set_fact:
        compose_id: "{{ output.stdout_lines[0] | regex_replace('.*Compose ([^ ]*) added to the queue.*', '\\1') }}"

    - name: Afficher l'ID du compose
      debug:
        var: compose_id
