---
- name: Clone repository and push kiosk.toml to Image Builder
  hosts: all
  vars:
    repo_url: "https://github.com/bdherouville/red-hat-kiosk.git"  # Replace <REPOSITORY_URL> with the actual repository URL
    destination_path: "~/red-hat-kiosk/"  # Replace with the path where the repository should be cloned
    kiosk_file_path: "~/red-hat-kiosk/imagebuilder/kiosk.toml"  # Adjust based on actual destination_path
  tasks:
    - name: Clone the specified repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ destination_path }}"
        clone: yes
        update: yes

    - name: Push kiosk.toml to Image Builder
      ansible.builtin.command:
        cmd: "composer-cli blueprints push {{ kiosk_file_path }}"
