---
- name: Update dnf, Install Packages, and Enable osbuild-composer.socket
  hosts: all
  become: yes
  tasks:
    - name: Update dnf
      dnf:
        name: '*'
        state: latest
      register: dnf_update_result

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - osbuild-composer
        - composer-cli
        - cockpit-composer
        - bash-completion
        - lorax
        - containernetworking-plugins

    - name: Add cloud-user to the weldr group
      user:
        name: cloud-user
        groups: weldr
        append: yes
        
    - name: Enable osbuild-composer.socket
      systemd:
        name: osbuild-composer.socket
        state: started
        enabled: yes

    - name: Enable cockpit.socket
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes