---
- name: Update dnf, Install Packages, and Enable osbuild-composer.socket
  hosts: all
  become: yes
  tasks:
    - name: Update dnf
      dnf:
        name: '*'
        state: latest
      register: dnf_update_result

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - osbuild-composer
        - composer-cli
        - cockpit-composer
        - bash-completion
        - lorax

    - name: Enable osbuild-composer.socket
      systemd:
        name: osbuild-composer.socket
        state: started
        enabled: yes
    - name: Open port 9090 in the firewall
      firewalld:
        service: 9090 
        state: enabled