---
- name: Update dnf, Install Packages, and Enable osbuild-composer.socket
  hosts: all
  become: yes
  tasks:
    - name: Update dnf
      dnf:
        name: '*'
        state: latest
      register: dnf_update_result

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - osbuild-composer
        - composer-cli
        - cockpit-composer
        - bash-completion
        - lorax
        - python3
        - firewall-cmd

    - name: Enable osbuild-composer.socket
      systemd:
        name: osbuild-composer.socket
        state: started
        enabled: yes

    - name: Open port 9090 in the firewall
      shell: firewall-cmd --zone=public --add-port=9090/tcp --permanent
      when: ansible_os_family == 'RedHat'